name: "test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      timeout-minutes: 5
      with:
        consecutive-errors: 3
        polling-rate-seconds: 45
        images: |
          quay.io/cilium/cilium:v1.14.1
          quay.io/cilium/cilium:v1.14.2
